# Generated by Django 3.2 on 2022-05-19 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo_app', '0007_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='consumed_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='due_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='remaining_hours',
            field=models.IntegerField(default=0),
        ),
    ]
