# Generated by Django 3.2 on 2022-05-20 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo_app', '0008_auto_20220519_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='consumed_hours',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_time',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='remaining_hours',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
