# Generated by Django 3.2 on 2022-05-16 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_app', '0002_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='full_name',
        ),
    ]
