# Generated by Django 3.2.6 on 2022-05-18 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_app', '0005_log_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='log',
            name='is_superuser',
        ),
    ]
