# Generated by Django 3.2.6 on 2022-05-18 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_app', '0007_auto_20220518_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='log',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='log',
            name='is_staff',
        ),
    ]
