# Generated by Django 3.2.6 on 2022-05-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_app', '0008_auto_20220518_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='log',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='log',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
