# Generated by Django 3.2 on 2022-05-20 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_app', '0010_rename_is_staff_log_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default=2, upload_to='images'),
            preserve_default=False,
        ),
    ]
