# Generated by Django 3.2 on 2022-05-20 08:31

import a_app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_app', '0013_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='log',
            managers=[
                ('objects', a_app.models.manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='log',
            name='is_superuser',
        ),
    ]
